server:
  port: 8081

spring:
  thymeleaf:
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html

  datasource:
    name: testor
    url: jdbc:mysql://localhost:3306/testor
    username: root
    password: 123698745
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    配置建表语句，建完一次就注释掉，不要再创建了
#    schema:
#      - classpath:sql/xxx.sql
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

#    配置国际化文件基础名，SpringBoot默认自动配置在类路径下的message基础名，但现在我叫i18n目录下的login
  messages:
    basename: i18n.message
    encoding: UTF-8
  resources:
    static-locations: i18n
  redis:
    host: 127.0.0.1
    port: 6379
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000ms
#    lettuce:
#      pool:
#      # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-wait: -1ms
#        # 连接池中的最大空闲连接 默认 8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认 0
#        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml  # 指定sql映射文件的位置
#  config-location: classpath:mybatis/mybatis-config.xml # 指定mybatis全局配置文件的位置
#  type-aliases-package: com.example.mapper
  configuration:
#    map-underscore-to-camel-case: true  # 启动驼峰命名和下划线命名匹配
    cache-enabled: false  # Globally enables or disables any caches configured in any mapper under this configuration
    default-statement-timeout: 5  # Sets the number of seconds the driver will wait for a response from the database
    use-generated-keys: true # Allows JDBC support for generated keys. A compatible driver is required.This setting forces generated keys to be used if set to true,as some drivers deny compatibility but still work
